### ISSUE TITLE
When multiple rerenders happen on the page the parallax animation stops working

### ISSUE THREAD

**Issue by OttlikG** [geosigno/simpleParallax.js#126]
I use the react version of parallax component.

When I comment out the following it works correctly.
https://github.com/geosigno/simpleParallax.js/blob/master/src/react/index.tsx#L52-L54

I think this lib really the easiest to integrate out of the mani parallax solution although there is a little problem when multiple rerenders mounting an unmounting happens on the page.
When I click on the Edit button which enables the page to inline edit text and edit gallery etc. the parallax stops working. I digged into the code and figured that it fix it when I comment out the aforementioned lines.

Hope this helps to fix this little issue with the lib.

If any input needed don't hesitate to ask.

**Comment by OttlikG** [comment]
The commented out code prevent updating the `boundingClientRect` to update. Which stops keeping the animation alive.
```
setBoundingClientRect(boundingClientRect);
```

**Comment by geosigno** [comment]
Hi,

Thanks for your interest in the library! 😊

Could you share a reproducible example so I can investigate the issue further?

The isInit state has been put in place to bypass the isVisible check on page load. Without it, when you first load the page and scroll to the image, the image will jump from its original position to the parallax one. If the transition is set, it creates a large parallax effect that is not desirable. The isInit state allows the parallax image to be calculated only once and avoids that issue. I hope this explanation is clear. I attached 2 videos, one with isInit and second one without, notice the transition on the second 
https://github.com/user-attachments/assets/37c401e3-af70-461d-94a7-83346f7d9919

That's why I need a reproducible example, or at least more details on how to reproduce the issue, before providing a fix.

Thanks!

https://github.com/user-attachments/assets/44b9e271-5cd7-4d6b-b665-732aeb2f7067

https://github.com/user-attachments/assets/21413a78-72d1-45d2-88f1-3ff4353a656e

**Comment by OttlikG** [comment]
Unfortunately couldn't reproduce the bug in an isolated environment.

I will close for now, when I've got time to investigate a bit further and have some findings will reopen.
