### ISSUE TITLE
Why not works at all with scale:1 ?

### ISSUE THREAD

**Issue by 7iomka** [geosigno/simpleParallax.js#42]
Demo: https://codepen.io/7iomka/pen/ExjQRqO
Thanks!

**Comment by geosigno** [comment]
Hi,
This won't work with a scale set at 1, because the all logic is expecting to have some scale to be able to translate the image without breaking the layout. 
Have a look [here](https://medium.com/@geoffrey.signorato/case-study-create-a-parallax-effect-directly-on-img-tags-with-javascript-35b8daf81471) to have more info.
