### ISSUE TITLE
translateValueY jump on pageload

### ISSUE THREAD

**Issue by bobhuf** [geosigno/simpleParallax.js#57]
Hi,

When the page loads my paralax element 'jumps' because it gets
```css
transform: translate3d(0px, 39px, 0px);
```
applied in stead of:
```css
transform: translate3d(0px, 0, 0px);
```

My config is:
```javascript
var shapes = document.querySelectorAll('.project-hero-shape svg');
new simpleParallax(shapes, {
    orientation: 'up',
    delay: .1,
    overflow: true,
    transition: 'cubic-bezier(0,0,0,1)'
});
```

Is there a way around this?

Thanks!

**Comment by geosigno** [comment]
Hi Bob,

This is actually the expected behavior... simpleParallax calculates a percentage based on the image position compared to the viewport. This percentage is then converted into a transition range and apply to the image. More info [here](https://itnext.io/case-study-create-a-parallax-effect-directly-on-img-tags-with-javascript-35b8daf81471).

So the transition value is applied as soon as the plugin is initialized.

**Comment by bobhuf** [comment]
Thanks for getting back to me.

I get it but in my case it's an issue. Allow me to explain: I have a regular image and on top of that an absolutely positioned svg shape on top of it. The shape has the parallax effect applied and both image have the same aspect ratio to ensure perfect positioning across different sized viewports.

Now, I already accounted for the position of the moving part by positioning it inside the viewBox. So I don't need a starting position to be adjusted by the script.

So I guess I'm asking how to disable the initial positioning?

**Comment by geosigno** [comment]
I added an init class when simpleParallax is initialized, so you can use it to fade out / fade in your svg.

Because the parallax is calculated via the scroll position of the page AND the position of the image in the viewport, the plugin needs to translate the image based on those 2 metrics at some point (once the page is loaded). 

So theoretically, to not have any jump at the page load, you would need to have the parallax image at the exact vertical center of the viewport.
